### ISSUE TITLE
Performance optimization opportunities in Analyzer

### ISSUE THREAD

**Issue by lrytz** [scala/scala-asm#1]
Identified by @retronym https://github.com/scala/scala/pull/6075#issuecomment-329375467

---

https://github.com/scala/scala-asm/blob/v5.1.0-scala-2/src/main/java/scala/tools/asm/tree/analysis/Frame.java#L623-L632
  - `Type.getArgumentTypes(desc).length` / `Type.getReturnType(desc) == Type.VOID_TYPE` could be directly implemented without constructing a `Type` isntance
  - The same can be done in the Scala compiler (https://github.com/scala/scala/blob/v2.12.3/src/compiler/scala/tools/nsc/backend/jvm/analysis/InstructionStackEffect.scala#L63-L64)

---

In [`Type.java`](https://github.com/scala/scala-asm/blob/v5.1.0-scala-2/src/main/java/scala/tools/asm/Type.java), a number of `String` to `char[]` conversions are performed to call into `getType`. If this method was duplicated to operatoe on `String` directly, those conversions could be avoided.

```
public static Type getReturnType(final String methodDescriptor) {
        char[] buf = methodDescriptor.toCharArray();
        return getType(buf, methodDescriptor.indexOf(')') + 1);
    }
```

Could use `lastIndexOf` to search from the end of the descriptor.

**Comment by retronym** [comment]
I'm pursuing this upstream as https://gitlab.ow2.org/asm/asm/issues/317828 / https://github.com/retronym/asm/compare/opt/reduce-alloc

**Comment by SethTisue** [comment]
that ticket was closed as fixed, so I can presume this one can be as well
